//
//  ListCourses.swift
//  PadrinhoAmigo
//
//  Created by Breno Harris on 05/07/23.
//

import Foundation

struct Courses {
    let allCourses = ["Ciências Biológicas (bacharelado)",
                      "Ciências Biológicas (licenciatura)",
                      "Odontologia",
                      "Medicina",
                      "Enfermagem",
                      "Educação física (integral)",
                      "Educação física (noturno)",
                      "Fonoaudiologia",
                      "Farmácia",
                      "Ciências do esporte",
                      "Nutrição",
                      "Matemática (licenciatura)",
                      "Estatística",
                      "Física (licenciatura)",
                      "Química",
                      "Engenharia Agrícola",
                      "Engenharia Química (integral)",
                      "Engenharia Química (noturno)",
                      "Engenharia Mecânica",
                      "Engenharia Elétrica (integral)",
                      "Engenharia Elétrica (noturno)",
                      "Engenharia Civil",
                      "Engenharia de Computação",
                      "Engenharia de Alimentos (integral)",
                      "Engenharia de Alimentos (noturno)",
                      "Engenharia de Telecomunicações",
                      "Engenharia Ambiental",
                      "Engenharia de Manufatura",
                      "Engenharia de Produção",
                      "Engenharia de Transportes",
                      "Tecnologia em Análise e Desenvolvimento de Sistemas",
                      "Ciência da Computação",
                      "Engenharia de Controle e Automação",
                      "Química Tecnológica",
                      "Química e Física (licenciatura integrada)",
                      "Engenharia Física",
                      "Física",
                      "Física Médica e Biomédica",
                      "Matemática Aplicada",
                      "Física Aplicada e Computacional",
                      "Curso 51",
                      "Geologia",
                      "Tecnologia em Saneamento Ambiental",
                      "Sistemas de Informação",
                      "Letras (integral)",
                      "Letras (noturno)",
                      "Ciências Sociais (integral)",
                      "Ciências Sociais (noturno)",
                      "Ciências Econômicas (integral)",
                      "Ciências Econômicas (noturno)",
                      "Linguística",
                      "História",
                      "Pedagogia (integral)",
                      "Pedagogia (noturno)",
                      "Filosofia",
                      "Geografia (integral)",
                      "Geografia (noturno)",
                      "Estudos literários",
                      "Administração",
                      "Administração Pública",
                      "Arquitetura e Urbanismo",
                      "Música",
                      "Dança",
                      "Artes visuais",
                      "Artes cênicas",
                      "Comunicação Social – Midialogia"]

}
